### ISSUE TITLE
hap status errors out despite no running processes, uninstalling/reinstalling doesn't work, affects all environments

### ISSUE THREAD

**Issue by abarbadan** [bmwant/hapless#27]
This is the error output when running `hap`

`Traceback (most recent call last):
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/bin/hap", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/<user>.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/hapless/cli.py", line 38, in cli
    _status(None, verbose=verbose)
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/hapless/cli.py", line 61, in _status
    hapless.stats(haps, verbose=verbose)
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/hapless/main.py", line 73, in stats
    status_text = Hapless._get_status_text(hap.status)
                                           ^^^^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/hapless/hap.py", line 121, in status
    if self.rc != 0:
       ^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/hapless/utils.py", line 28, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.pyenv/versions/3.11.0/envs/sandbox311/lib/python3.11/site-packages/hapless/hap.py", line 143, in rc
    return int(f.read())
           ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''`

**Comment by bmwant** [comment]
Hi @abarbadan, could you provide current version of the package `hap --version`?
Did you try reinstalling like this
```
pip install hapless --upgrade --force-reinstall
```
Or installing into new virtual environment?
Which command are you trying to execute? Just `hap`/`hap status`?
I'm also assuming your python version as 3.11, right?

**Comment by bmwant** [comment]
@abarbadan as a fix 
```bash
# note: replace with your state directory
rm -rf  /var/folders/kv/pvmb7wns2z534y0lqkwc1rq40000gp/T/hapless
```
of the state directory should do the trick. If wouldn't help then I will create a fix within the code

**Comment by bmwant** [comment]
If that's an issue of improperly finished process, try running `hap clean` first (this command will cleanup leftover state files for finished processes)

**Comment by abarbadan** [comment]
hap clean throws the same error, however, finding the state dir and removing it fixed the problem completely. Now it runs as expected. FYI, for me, it was in /tmp/hapless. I would suggest maybe writing a command that clears state, or incorporating it in hap clean. That being said, the issue is resolved for me.

Thank you very much for your help!
