### ISSUE TITLE
BUG: If task is killed without writing rc, hapless throws exception on status

### ISSUE THREAD

**Issue by josht000** [bmwant/hapless#30]
(Love the tool BTW) If the background tasks are killed manually and hapless doesn't write to the /tmp/hapless/X/rc file then hapless will crash when status is called. 

Suggest just catching that exception (shown below) and not displaying the RC code in the status. Similar issues with permission denied in that the whole program crashes if it can't access one of the /tmp/hapless/X files.

❯ hap status
Traceback (most recent call last):
  File "/home/thamesj/envs/ngsri_training/bin/hap", line 8, in <module>
    sys.exit(cli())
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/hapless/cli.py", line 45, in status
    _status(hap_alias, verbose)
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/hapless/cli.py", line 61, in _status
    hapless.stats(haps, verbose=verbose)
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/hapless/main.py", line 82, in stats
    hap.runtime,
  File "/home/thamesj/envs/ngsri_training/lib/python3.9/site-packages/hapless/hap.py", line 152, in runtime
    finish_time = os.path.getmtime(self._rc_file)
  File "/opt/python/3.9.4/lib/python3.9/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hapless/57/rc'

**Comment by bmwant** [comment]
Hey @josht000, thanks for your bug report. Missed required check for the runtime attribute (e.g. like the one here https://github.com/bmwant/hapless/blob/main/hapless/hap.py#L167)
https://github.com/bmwant/hapless/pull/31
Will try to merge it soon and release new package version

**Comment by bmwant** [comment]
@josht000 new version `0.3.0` was released with a bug fixed.
Upgrade your package with 
```bash
pip install --upgrade hapless
```

**Comment by josht000** [comment]
I'll check it out today
